'// MergePropIDCells.bas
'//---------------------------------------------------------------
'// MergePropIDCells - Merge PropID cells in Territory sheet header.
'//		9/19/20.	wmk.	06:30
'//---------------------------------------------------------------

public sub MergePropIDCells()

'//	Usage.	macro call or
'//			call MergePropIDCells()
'//
'// Entry.	user has any sheet selected
'//
'//	Exit.	PropID name cells merged (E2:G2)
'//			PropID NumberFormat set to "0000000000"
'//
'// Calls.
'//
'//	Modification history.
'//	---------------------
'//	9/11/20.	wmk.	original code; generated by Record Macro
'//	9/19/20.	wmk.	set ID cell format to TEN_ZEROS
'//
'//	Notes.

'//	constants.
const TEN_ZEROS=121			'// 10 0's number format
const COL_E=4
const ROW_1=0

'//	local variables.
dim oDocument   as object
dim oDispatcher as object
dim oDoc	As Object	'// ThisComponent
dim oSel	As Object	'// current cell selection on entry
dim oSheet	As Object	'// current sheet
dim oRange	As Object	'// RangeAddress selected
dim iSheetIx	As Integer	'// sheet index this sheet
dim oCols	As Object	'// .Columns array this sheet
dim oCell	As Object	'// cell selected

	'// code.
	ON ERROR GOTO ErrorHandler
	oDoc = ThisComponent
	oSel = oDoc.getCurrentSelection()
	oRange = oSel.RangeAddress
	iSheetIx = oRange.Sheet
	oSheet = oDoc.Sheets(iSheetIx)
'	oCols = oSheet.Columns
'	oCols(COL_A).setPropertyValue("NumberFormat", TEN_ZEROS)
	oCell = oSheet.getCellByPosition(COL_E, ROW_1)
	oCell.NumberFormat = TEN_ZEROS
	
	oDocument   = ThisComponent.CurrentController.Frame
	oDispatcher = createUnoService("com.sun.star.frame.DispatchHelper")

	'// select range E1:G1
	dim args1(0) as new com.sun.star.beans.PropertyValue
	args1(0).Name = "ToPoint"
	args1(0).Value = "$E$1:$G$1"

	oDispatcher.executeDispatch(oDocument, ".uno:GoToCell", "", 0, args1())

	oDispatcher.executeDispatch(oDocument, ".uno:ToggleMergeCells", "", 0, Array())



NormalExit:
	exit sub
	
ErrorHandler:
	msgbox("MergePropIDCells - unprocessed error.")
	
end sub		'// end MergePropIDCells	9/19/20
