'// MergeOwnerCells.bas
'//---------------------------------------------------------------
'// MergeOwnerCells - Merge Owner cells in Territory sheet header.
'//		9/11/20.	wmk.	06:30
'//---------------------------------------------------------------

public sub MergeOwnerCells()

'//	Usage.	macro call or
'//			call MergeOwnerCells()
'//
'// Entry.	user has territory sheet selectd
'//
'//	Exit.	Owner name cells merged (E2:G2)
'//
'// Calls.
'//
'//	Modification history.
'//	---------------------
'//	9/11/20.		wmk.	original code; generated by Record Macro
'//
'//	Notes.

'//	constants.

'//	local variables.
dim oDocument   as object
dim oDispatcher as object

	'// code.
	ON ERROR GOTO ErrorHandler
	oDocument   = ThisComponent.CurrentController.Frame
	oDispatcher = createUnoService("com.sun.star.frame.DispatchHelper")

	'// select range E2:G2
	dim args1(0) as new com.sun.star.beans.PropertyValue
	args1(0).Name = "ToPoint"
	args1(0).Value = "$E$2:$G$2"

	oDispatcher.executeDispatch(oDocument, ".uno:GoToCell", "", 0, args1())

	oDispatcher.executeDispatch(oDocument, ".uno:ToggleMergeCells", "", 0, Array())


NormalExit:
	exit sub
	
ErrorHandler:
	msgbox("MergeOwnerCells - unprocessed error.")
	
end sub		'// end MergeOwnerCells
