'// MergeStreetsCells.bas
'//---------------------------------------------------------------
'// MergeStreetsCells - Merge Owner cells in Territory sheet header.
'//		9/12/20.	wmk.	23:15
'//---------------------------------------------------------------

public sub MergeStreetsCells()

'//	Usage.	macro call or
'//			call MergeStreetsCells()
'//
'// Entry.	user has territory sheet selectd
'//
'//	Exit.	Streets/Addrs cells merged (E3:G3)
'//
'// Calls.
'//
'//	Modification history.
'//	---------------------
'//	9/11/20.		wmk.	original code; generated by Record Macro
'//
'//	Notes.

'//	constants.

'//	local variables.
dim oDocument   as object
dim oDispatcher as object

	'// code.
	ON ERROR GOTO ErrorHandler
	oDocument   = ThisComponent.CurrentController.Frame
	oDispatcher = createUnoService("com.sun.star.frame.DispatchHelper")

	'// select range E3:G3
	dim args1(0) as new com.sun.star.beans.PropertyValue
	args1(0).Name = "ToPoint"
	args1(0).Value = "$E$3:$G$3"

	oDispatcher.executeDispatch(oDocument, ".uno:GoToCell", "", 0, args1())

	oDispatcher.executeDispatch(oDocument, ".uno:ToggleMergeCells", "", 0, Array())


NormalExit:
	exit sub
	
ErrorHandler:
	msgbox("MergeStreetsCells - unprocessed error.")
	
end sub		'// end MergeStreetsCells
