'// QcsvToBridge.bas
'//---------------------------------------------------------------
'// QcsvToBridge - Query .csv sheet to Admin-Bridge sheet.
'//		9/30/20.	wmk.	07:30
'//---------------------------------------------------------------

public sub QcsvToBridge()

'//	Usage.	macro call or
'//			call QcsvToBridge()
'//
'// Entry.
'//	sheet selected with .csv fields generated by SQL/Query of any of the
'// .Props tables (e.g. SplitProps, TerrProps, BizProps, with rows selected
'// for a given territory. Following are the columns and .Props columns:
'//
'//	OwningParcel  UnitAddress  Resident1 Resident2 Phone1 Phone2 RefUSA-Phone
'//			A			B			C		D		  E		 F		G	
'//  SubTerrItory CongTerrID DoNotCall RSO Foreign  RecordDate SitusAddress  DelPending
'//		H				I		   J     K     L		M			  N			  O
'//
'//	Exit.	produces an "Admin-Bridge" formatted sheet with the x..Props columns:
'//	OwningParcel  UnitAddress  Resident1 Resident2 Phone1 Phone2 RefUSA-Phone
'//	 A (from A)	  B (from K)	C (from B)  D (from C)	E	 F		G	
'//
'//  SubTerrItory CongTerrID DoNotCall RSO Foreign  RecordDate SitusAddress
'//		H				I		   J     K     L	(header C2)		N (from N)
'//
'//  Property Use	DelPending
'//		  O				P
'//
'//		along with 4 header rows, populated with the Admin-Bridge header information.
'//&lt;Area-CommonName&gt;			Property ID	&lt;OwnerParcel&gt;			Admin-Bridge formatted sheet
'//Units shown:	63	9/16/20	Owner		&lt;OwnerName1&gt;
'//City	Venice	34285	Streets/Addrs	&lt;Streets-Address(s)&gt;
'//SubTerritory		CongTerrID

'// Calls.	SetTerrHeader, SetBridgeHeadings
'//
'//	Modification history.
'//	---------------------
'//	9/18/20.	wmk.	original code; adapted from EditToTerr
'// 9/24/20.	wmk.	mod to add PropUse column, SetTerrHeader, 
'//						SetBridgeHeadings
'// 9/30/20.	wmk.	dead code removed
'//
'//	Notes.
'// Method.
'//		insert 4 rows at top
'//		use SetBridgeHeadings for setting header fields

'//	constants.
const COL_PARCEL=0		'// "OwningParcel" column index
const COL_A=0
const COL_B=1
const COL_C=2	
const COL_D=3
const COL_E=4
const COL_F=5
const COL_G=6			'// column G index
const COL_H=7			'// column H index
const COL_I=8			'// column I index
const COL_J=9			'// column J index
const COL_K=10			'// column K index
const COL_L=11			'// column L index (DoNotCall)
const COL_M=12			'// column M index (RSO)
const COL_N=13			'// column N index (Foreign)
const ROW_1=0
const ROW_2=1
const ROW_3=2
const ROW_4=3
const ROW_HEADING=4		'// headings row index
const LJUST=1		'// left-justify HoriJustify				'// mod052020
const CJUST=2		'// center HoriJustify						'// mod052020
const RJUST=3		'// right-justify HoriJustify				'// mod052320
const MDYY=30		'// 'M/D/YY' format value

'//	local variables.
Dim oDoc As Object
Dim oSheet As Object
Dim NewColumn As Object
dim oSel as Object
dim iSheetIx as integer
dim oRange as Object
dim lThisRow as long		'// current row selected on sheet
dim oMrgRange	As Object	'// merge range

dim oCell	As Object		'// cell working on
dim i		As Integer		'// loop index
dim sPropID	As String		'// property ID
dim sSubTerr	As String	'// subterritory
dim sCongTerr	As String	'// cong terr ID
dim lRowCount	As Long		'// row count of addresses
dim dDate		As Double	'// date value
dim sCityStZip	As String	'// concatenated City, State, Zip
dim sNotes		As String	'// notes field
dim nCols		As Integer	'// removal column count

	'// code.
	ON ERROR GoTo ErrorHandler
	oDoc = ThisComponent
	oSel = oDoc.getCurrentSelection()
	oRange = oSel.RangeAddress
	iSheetIx = oRange.Sheet
	oSheet = oDoc.Sheets(iSheetIx)

	InsertTerrHdr("Admin-Bridge formatted sheet")		'// set territory sheet header information
	SetBridgeHeadings()
	
NormalExit:
	exit sub

ErrorHandler:
	msgbox("QcsvToBridge - unprocessed error.")
	GoTo NormalExit

end sub		'// end QcsvToBridge		9/30/20
