'// QGetToBizBridge.bas
'//---------------------------------------------------------------
'// QGetToBizBridge - Query .csv sheet to Admin-Bridge sheet.
'//		9/26/21.	wmk.	13:09
'//---------------------------------------------------------------

public sub QGetToBizBridge()

'//	Usage.	macro call or
'//			call QGetToBizBridge()
'//
'// Entry.
'//	sheet selected with .csv fields generated by SQL/Query of any of the
'// .Props tables (e.g. SplitProps, TerrProps, BizProps, with rows selected
'// for a given territory. Note: differs from QcsvToBridge only slightly;
'// The Get .csv sheet has  no column headings, so 5 rows are inserted
'// insted of 4; all the rest of the code is cloned from QcsvToBridge.
'//
'// Method. 
'//	remove columns F (City) and G (Zip) bringing gender and title into correct
'//	 columns, moving H and I data into F and G;
'//	Columns J-M automatically shifted by removing F and G
'//now move over to H;
'//	Column headings H-L Territory, DoNotCall,RecordDate,SunBiz,DelPending
'//
'// Following are the columns and .Props columns:
'//CompanyName	UnitAddress	Owner  ContactPhone  BizDesc [ ]  [ ] Gender Title
'//		A			B		  C			D		   E		 		F	   G	
'//   Terr DoNotCall RecDate SunbizDoc	Del
'//		H		I	   J    	 K    	 L	
'//
'//	Exit.	produces a "Biz-Bridge" formatted sheet with the x..Props columns:
'//CompanyName	UnitAddress	Owner  ContactPhone  BizDesc Gender Title
'//		A			B		  C			D		   E 		F	   G	
'//   [Terr] DoNotCall  [ RecDate ]	[SunbizDoc]	[Del]
'//				H	  (header C2)
'//
'//		along with 4 header rows, populated with the Biz-Bridge header information
'//		and headings row.
'//&lt;Area-CommonName&gt;				Biz-Bridge formatted sheet
'//Units shown:	63	9/16/20	Owner		&lt;OwnerName1&gt;
'//City	Venice	34285	Streets/Addrs	&lt;Streets-Address(s)&gt;
'//SubTerritory		CongTerrID

'// Calls.	InsertQBizHeader, SetBridgeHeadings, BoldHeadings, FreezeView,
'//			SetBizColWidths
'//
'//	Modification history.
'//	---------------------
'// 9/25/21.	wmk.	original code; adapted from QGetToBridge;
'//						InsertQTerrHeader replaced with InsertQBizHeader;
'//						SetBridgeHeadings replaced with SetBizHeadings;
'//						SetBridgeColWidths replaced with SetBizColWidths.
'// 9/26/21.	wmk.	sheet column documentation; columns F and G removed before
'//						adding header to make life easy.
'// Legacy mods.
'//	9/25/20.	wmk.	original code; cloned from QcsvToBizBridge.
'// 9/26/21.	wmk.	document method and implement.
'//	10/5/20.	wmk.	add TerrID to InsertQTerrHdr call
'//	10/24/20.	wmk.	updated documentation for Unit/Header1 placement
'// 11/4/20.	wmk.	accommodate source sheet names Terrxxx or QTerrxxx
'//						to match new QGetTerr SQL query file naming.
'//	7/9/21.		wmk.	eliminated ending FreezeView to see if helps downstream
'//						cell selection;restored FreezeView.
'//
'//	Notes. The first business territory created with the new Bridge table
'// data from the Terrxxx_RU.db is 502. That territory Terr502_BizTerr.ods
'// has the detailed instructions as to how the column data was massaged
'// into BizBridge format. The sheet with the instructions is named
'// QTerr502B_BizTerrTemplate.
'//
'//
'// Method.
'//		insert 4 rows and headings row at top
'//		column data remains intact in place
'//		use SetBridgeHeadings for setting header fields

'//	constants.
const COL_PARCEL=0		'// "OwningParcel" column index
const COL_A=0
const COL_B=1
const COL_C=2	
const COL_D=3
const COL_E=4
const COL_F=5
const COL_G=6			'// column G index
const COL_H=7			'// column H index
const COL_I=8			'// column I index
const COL_J=9			'// column J index
const COL_K=10			'// column K index
const COL_L=11			'// column L index (DoNotCall)
const COL_M=12			'// column M index (RSO)
const COL_N=13			'// column N index (Foreign)
const ROW_1=0
const ROW_2=1
const ROW_3=2
const ROW_4=3
const ROW_HEADING=4		'// headings row index
const LJUST=1		'// left-justify HoriJustify				'// mod052020
const CJUST=2		'// center HoriJustify						'// mod052020
const RJUST=3		'// right-justify HoriJustify				'// mod052320
const MDYY=30		'// 'M/D/YY' format value

'//	local variables.
Dim oDoc As Object
Dim oSheet As Object
Dim NewColumn As Object
dim oSel as Object
dim iSheetIx as integer
dim oRange as Object
dim lThisRow as long		'// current row selected on sheet
dim oMrgRange	As Object	'// merge range

dim oCell	As Object		'// cell working on
dim i		As Integer		'// loop index
dim sPropID	As String		'// property ID
dim sSubTerr	As String	'// subterritory
dim sCongTerr	As String	'// cong terr ID
dim lRowCount	As Long		'// row count of addresses
dim dDate		As Double	'// date value
dim sCityStZip	As String	'// concatenated City, State, Zip
dim sNotes		As String	'// notes field
dim nCols		As Integer	'// removal column count
dim sTerrID		As String	'// territory ID
dim sSheetName	As String	'// sheet name

	'// code.
	ON ERROR GoTo ErrorHandler
	oDoc = ThisComponent
	oSel = oDoc.getCurrentSelection()
	oRange = oSel.RangeAddress
	iSheetIx = oRange.Sheet
	oSheet = oDoc.Sheets(iSheetIx)
	sSheetName = oSheet.Name
	if strcomp(left(sSheetName,1),"Q") = 0 then
		sTerrID = Mid(oSheet.Name,6,3)	
	else
		sTerrID = Mid(oSheet.Name,5,3)
	endif

	'// remove columns F and G.
	oSheet.Columns.removeByIndex(COL_F, 2)
	
'//	InsertQTerrHdr(sTerrID, "Admin-Bridge formatted sheet")		'// set territory sheet header information
	InsertQBizHdr(sTerrID, "Biz-Bridge formatted sheet")
'//	SetBridgeHeadings()
	SetBizHeadings()
'//	SetBridgeColWidths()
	SetBizColWidths()
	BoldHeadings()
	FreezeView()
		
NormalExit:
	exit sub

ErrorHandler:
	msgbox("QGetToBizBridge - unprocessed error.")
	GoTo NormalExit

end sub		'// end QGetToBizBridge		9/26/21.	13:09
