# pathdefs.inc
# 9/3/21.	wmk.	original code.
# 8/16/23.	wmk.	adapted for Chromebook and MN/CRWG/44586.	
vpath %.db /home/vncwmk3/Territories/MN/CRWG/44586/RawData/RefUSA/RefUSA-Downloads/Terryyy
vpath %.csv /home/vncwmk3/Territories/MN/CRWG/44586/RawData/RefUSA/RefUSA-Downloads/Terryyy
bashpath = /home/vncwmk3/Territories/MN/CRWG/44586/Procs-Dev/
postpath = /home/vncwmk3/Territories/MN/CRWG/44586/RawData/RefUSA/RefUSA-Downloads/Terryyy/
