#!/bin/bash
# ClearSpecial.sh - Clear out files so InitSpecial does full initialize.
#	1/4/22.	wmk.
#
# Modification History.
# ---------------------
# 9/11/21.	wmk.	original code.
# 10/25/21.	wmk.	AddZips, MakeAddZips, Specialxxx.dblist.txt added to list
#					of files to clear; RegenSpecDB, SyncTerrToSpec .sq > .sql.
# 11/1/21.	wmk.	mod to remove all records from letter territory 6xx.
# 1/4/22.	wmk.	$ rp test made consistent with " strings.
P1=$1
read -p "You will clear files in territory $P1! Are you sure (Y/N)? "
rp=${REPLY,,}
if [ "$rp" != "y" ];then echo "ClearSpecial abandoned.";exit 0;fi
cd $folderbase/Territories/RawData/RefUSA/RefUSA-Downloads/Terr$P1
fn1=Spec$P1
fn2=RU.sql
if test -f SPECIAL;then rm SPECIAL;fi
if test -f $fn1$fn2;then rm $fn1$fn2;fi
if test -f RegenSpecDB.sql;then rm RegenSpecDB.*;fi
if test -f SetSpecTerrs.sql;then rm SetSpecTerrs.*;fi
if test -f SetMHPSpecTerrs.sql;then rm SetMHPSpecTerrs.*;fi
if test -f SyncTerrToSpec.sql;then rm SyncTerrToSpec.*;fi
if test -f AddZips.sql;then rm AddZips.*;fi
if test -f Specialxxx.dblist.txt;then rm Specialxxx.dblist.txt;fi
if test -f MakeSpecials;then rm MakeSpecials;fi
if test -f MakeRegenSpecDB;then rm MakeRegenSpecDB*;fi
if test -f MakeSetSpecTerrs;then rm MakeSetSpecTerrs*;fi
if test -f MakeSetMHPSpecTerrs;then rm MakeSetMHPSpecTerrs*;fi
if test -f MakeSyncTerrToSpec;then rm MakeSyncTerrToSpec*;fi
if test -f MakeAddZips;then rm MakeAddZips*;fi
# code to conditionally clear records from letter Terr$P1.db.
firstchar=${P1:0:1}
if [ "$firstchar" == "6" ];then
   fbase=Terr$P1
   fsuffx=_RU.db
   tblsuffx=_RUBridge
   echo "-- * Empty Terr$P1 _RUBridge table;" > SQLTemp.sql
   echo ".open ""$folderbase/Territories/RawData/RefUSA/RefUSA-Downloads/$fbase/$fbase$fsuffx"" " \
    >> SQLTemp.sql
   echo "DELETE FROM $fbase$tblsuffx;" >> SQLTemp.sql
   echo ".quit" >> SQLTemp.sql
   sqlite3 < SQLTemp.sql
   echo "$fbase$tblsuffx records cleared."
fi
echo "Territory $P1 specials cleared."
# end ClearSpecial.sh
