CREATE TABLE "$DIFF_TBL"
 ( "Account #" TEXT NOT NULL, 
 "Owner 1" TEXT, "Owner 2" TEXT, "Owner 3" TEXT, 
 "Mailing Address 1" TEXT, "Mailing Address 2" TEXT, 
 "Mailing City" TEXT, "Mailing State" TEXT, 
 "Mailing Zip Code" TEXT, "Mailing Country" TEXT,
 "Situs Address (Property Address)" TEXT,
 "Situs City" TEXT, "SitusState" TEXT, "Situs Zip Code" TEXT, 
 "Property Use Code" TEXT, "Neighborhood" TEXT, 
 "Subdivision" TEXT, "TaxingDistrict" TEXT, 
 "Municipality" TEXT, "WaterfrontCode" TEXT, 
 "Homestead Exemption" TEXT, 
 "HomesteadExemptionGrantYear" TEXT, 
 "Zoning" TEXT, "ParcelDesc1" TEXT, "ParcelDesc2" TEXT, 
 "ParcelDesc3" TEXT, "ParcelDesc4" TEXT, 
 "Pool(YESorNO)" TEXT, "TotalLivingUnits" TEXT, 
 "LandAreaS.F." TEXT, "GrossBldgArea" TEXT, 
 "LivingArea" TEXT, "Bedrooms" TEXT, "Baths" TEXT, 
 "HalfBaths" TEXT, "YearBuilt" TEXT, 
 "LastSaleAmount" TEXT, 
 "Last Sale Date" TEXT, "LastSaleQualCode" TEXT, 
 "PriorSaleAmount" TEXT, "PriorSaleDate" TEXT, 
 "PriorSaleQualCode" TEXT, "JustValue" TEXT, 
 "AssessedValue" TEXT, "TaxableValue" TEXT, 
 "LinktoPropertyDetailPage" TEXT, 
 "ValueDataSource" TEXT, 
 "ParcelCharacteristicsData" TEXT, "Status"TEXT,
  DownloadDate AS TEXT,
  PRIMARY KEY("Account #") )
